### ISSUE TITLE
breaks id.fedoraproject.org

### ISSUE THREAD

**Issue by KwisatzJim** [oblador/hush#101] opened 2021-05-07 06:30 UTC
tried to sign up for an account through id.fedoraproject.org and it wouldn't load until I disabled hush

**Comment by oblador** [comment] 2021-06-18 16:07
How can I replicate this? Using https://accounts.fedoraproject.org it seems to work

**Comment by thejim** [comment] 2021-06-18 22:15
Hi

I forget what I did but somehow got it working.  Sorry I can’t be of more help, it’s been a while since I’ve done that


Jim Kelley

**Comment by oblador** [comment] 2021-08-13 09:16
Closing for now, open a new issue if you are able to reproduce again.

**Closed by oblador** 2021-08-13 09:16 UTC
