### ISSUE TITLE
Doesn't work on focus.de

### ISSUE THREAD

**Issue by sebastianlohmann** [oblador/hush#65] opened 2021-02-08 11:49 UTC
See [https://www.focus.de/digital/videos/hilfe-fuers-smartphone-ihr-iphone-geht-bei-kaelte-in-die-knie-dann-muessen-sie-diesen-tasten-trick-unbedingt-kennen_id_6547102.html](https://www.focus.de/digital/videos/hilfe-fuers-smartphone-ihr-iphone-geht-bei-kaelte-in-die-knie-dann-muessen-sie-diesen-tasten-trick-unbedingt-kennen_id_6547102.html)

**Comment by oblador** [comment] 2021-03-17 21:50
Hi, I'm unable to reproduce – what is not working?

**Comment by oblador** [comment] 2021-06-18 19:50
Closing due to lack of replies.

**Closed by oblador** 2021-06-18 19:50 UTC
